'''
This program will read the experiment files (generated by data_gathering.py with save_experiment option)
and generate the heatmap at specific time t

Requirements: pandas, numpy, matplotlib, seaborn
'''
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
for p in range(1,100):
    #change this to change the time
    t = p*100
    n = 11 #number of experiment on exp n_m
    m = 11 

    matrix = np.zeros((n,m))
    #change the range based on the number of experiment
    for i in range(1,n+1):
        for j in range(1,m+1):
            data = pd.read_csv('exp'+str(i)+'_'+str(j)+'.csv', header = None).T #transpose the dataframe
            data['mean'] = data.mean(axis=1) #create mean column,change this line to change the criteria
            matrix[i-1][j-1] = data.loc[(int(t/10)-1),'mean']
            del data #for freeing memory

    matrix = np.fliplr(matrix) #flip for sensible heatmap

    #change this to change x and y axis of heatmap
    x = ['2^-'+str(k) for k in range(1,m+1)]
    y = [round(2-0.2*k,1) for k in range(0,n)]
    x = np.flip(x)
    y = np.flip(y)
    plot = sns.heatmap(matrix, xticklabels= x, yticklabels=y,vmin = 0, vmax = 1.0)
    #change title here
    plt.title("Food collected per good ants at time t = "+str(t) + ' (n = 30, N = 1024)', fontsize =16)
    #change x axis here
    plt.xlabel('Proportion of malicious ants', fontsize = 10)
    #change y axis here
    plt.ylabel('Relative Fake pheromone intensity', fontsize = 10)

    #plt.tight_layout()
    #change this to change name. The default name is Heatmap_[time].png
    name = './Heatmap_'+str(t)+'.png'
    plot.figure.savefig(name, bbox_inches="tight")
    plot.figure.clf()
    del plot